# DriftDB Authentication Configuration

# Authentication method: trust, md5, scram-sha-256
auth_method = "scram-sha-256"

# Require authentication for all connections
require_auth = true

# Maximum failed login attempts before lockout
max_failed_attempts = 5

# Account lockout duration in seconds
lockout_duration = 300

# Password policy
[password_policy]
min_length = 12
require_uppercase = true
require_lowercase = true
require_numbers = true
require_special = true
max_age_days = 90

# Session configuration
[session]
max_idle_minutes = 30
max_lifetime_hours = 8
require_ssl = false  # Set to true in production

# IP-based access control
[access_control]
# Allow list (if empty, all IPs allowed)
allow_ips = []
# Deny list (processed after allow list)
deny_ips = []

# Audit logging
[audit]
log_successful_auth = true
log_failed_auth = true
log_commands = true